config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  root :to => "home#index"

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < BaseController
  

end

app/controllers/base_controller.rb
class BaseController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def site_name
    I18n.t('site_name')
  end
  helper_method :site_name

  def tag_line
    I18n.t('tag_line')
  end
  helper_method :tag_line

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include LayoutsHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:script) { javascript_include_tag(*args) }
  end

  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/views/about/index.html.erb
<% content_for :top do %>
  <div class="col-md-4">
    <h2 class="title"><span>Our Philosophy</span></h2>
    <p>Nullam ligula sapien, pharetra eget volutpat vel, consequat in lectus. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse potenti. Vivamus purus arcu, commodo cursus egestas et, dictum lobortis dui. Curabitur at mi eu mi sollicitudin faucibus at at libero.</p>
  </div>
  <div class="col-md-4">
    <h2 class="title"><span>Our Mission</span></h2>
    <p>Mauris viverra, tortor eget interdum lacinia, lacus mi tempor purus, eu commodo enim dui ac nisl. Morbi euismod ante quis tellus imperdiet porta. Morbi nisi nibh, facilisis a varius id, adipiscing.</p>
    <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur purus.</p>
  </div>
  <div class="col-md-4">
    <h2 class="title"><span>What We Do</span></h2>
    <p>Lorem ipsum dolor sit amet, tristique sem et, ridiculus metus, at id vestibulum, aliquam luctus. Justo hac in at duis orci montes, purus mauris eu turpis.</p>
    <p>Vestibulum non vestibulum justo in vitae, posuere ipsum vitae vestibulum amet, vestibulum pulvinar mi, mauris pharetra. Sodales sed malesuada quisque nunc, massa bibendum vestibulum sed hac. Quam mauris orci tellus vel integer dis.</p>
  </div>
<% end %>

<% content_for :bottom do %>

  <h2 class="title"><span>Our Team</span></h2>
  <p>Enim ultrices, elementum phasellus. Mauris sed nulla sed, egestas feugiat a dictum libero, nunc sapien tristique facilisis venenatis risus, suspendisse ac nec et. Nulla sed mauris, congue duis proin nonummy adipiscing vitae interdum. Augue eget ultrices tempor, dignissim et libero. Arcu quis, arcu et mauris molestie auctor aliquam, ut vitae, turpis ac rhoncus mi sagittis arcu, ut a nullam donec.</p>
  <div class="row">
    <div class="col-md-3">
      <div class="profile">
        <img alt="" src="img/team1.jpg">
        <h4>John Doe</h4>
        <div class="profile_title">Business Analyst</div>
        <p>Praesent vestibulum molestie lacus. Aenean noy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi.</p>
      </div>
    </div>
    <div class="col-md-3">
      <div class="profile">
         <img alt="" src="img/team2.jpg">
         <h4>Mary Bourgeois</h4>
         <div class="profile_title">Manager</div>
         <p>Praesent vestibulum molestie lacus. Aenean noy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi.</p>
      </div>
    </div>
    <div class="col-md-3">
      <div class="profile">
        <img alt="" src="img/team3.jpg">
        <h4>Donald Johnson</h4>
        <div class="profile_title">Business Analyst</div>
        <p>Praesent vestibulum molestie lacus. Aenean noy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi.</p>
      </div>
    </div>
    <div class="col-md-3">
      <div class="profile">
        <img alt="" src="img/team4.jpg">
        <h4>Elizabeth Gooch</h4>
        <div class="profile_title">Manager</div>
        <p>Praesent vestibulum molestie lacus. Aenean noy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi.</p>
      </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<% content_for :title do %>
   Home Page
<% end %>

<!--slider-->
<div id="main_slider">
  <div><%=image_tag('placeholder/slider/1.jpg' ) %></div>
  <div><%=image_tag('placeholder/slider/2.jpg' ) %></div>
  <div><%=image_tag('placeholder/slider/3.jpg' ) %></div>
</div>
<!--//slider-->

<!--planning-->
<div class="wrap planning">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <a href="#">
          <span class="img_icon icon1"></span>
          <span class="link_title">egestas dolor</span>
          Nunc vel arcu arcu. Nulla mollis feugiat dui id tincidunt. Aenean ac lobortis elit.
        </a>
      </div>
      <div class="col-md-3">
        <a href="#">
        	<span class="img_icon icon2"></span>
          <span class="link_title">lorem ipsum</span>
        	Nunc vel arcu arcu. Nulla mollis feugiat dui id tincidunt. Aenean ac lobortis elit.
        </a>
      </div>
      <div class="col-md-3">
        <a href="#">
        	<span class="img_icon icon3"></span>
          <span class="link_title">vestilum eget</span>
        	Nunc vel arcu arcu. Nulla mollis feugiat dui id tincidunt. Aenean ac lobortis elit.
        </a>
      </div>
      <div class="col-md-3">
        <a href="#">
        	<span class="img_icon icon4"></span>
          <span class="link_title">nulla feugiat</span>
        	Nunc vel arcu arcu. Nulla mollis feugiat dui id tincidunt. Aenean ac lobortis elit.
        </a>
      </div>
    </div>
  </div>
</div>
<!--//planning-->

<!--Welcome-->
<div class="wrap block">
  <div class="container welcome_block">
  	<div class="welcome_line welcome_t"></div>
  	Cras vulputate pretium massa gravida egestas consectetur?<span>Lorem ipsum dolor sit amet &amp; consectetur adipiscing elit!</span>
    <div class="welcome_line welcome_b"></div>
  </div>
</div>
<!--//Welcome-->

<!--featured works-->
<div class="wrap block carousel_block">
  <div class="container">
  	<h2 class="upper">featured works</h2>
  	<div class="row">
      <div class="col-md-12">
        <ul id="featured_work" class="owl-carousel owl-theme">
          <li class="item">
          	<div class="hover_img">
            	<a href="<%= image_url('placeholder/featured_works/1.jpg') %>" rel="prettyPhoto[portfolio1]"><img src="<%= image_url('placeholder/featured_works/1.jpg') %>" alt="" /><span class="portfolio_zoom1"></span></a>
            </div>
          </li>
          <li class="item">
          	<div class="hover_img">
            	<a href="<%= image_url('placeholder/featured_works/2.jpg') %>" rel="prettyPhoto[portfolio1]"><img src="<%= image_url('placeholder/featured_works/2.jpg') %>" alt="" /><span class="portfolio_zoom1"></span></a>
            </div>
          </li>
          <li class="item">
            <div class="hover_img">
            	<a href="<%= image_url('placeholder/featured_works/3.jpg') %>" rel="prettyPhoto[portfolio1]"><img src="<%= image_url('placeholder/featured_works/3.jpg') %>" alt="" /><span class="portfolio_zoom1"></span></a>
            </div>
          </li>
          <li class="item">
            <div class="hover_img">
            	<a href="<%= image_url('placeholder/featured_works/4.jpg') %>" rel="prettyPhoto[portfolio1]"><img src="<%= image_url('placeholder/featured_works/4.jpg') %>" alt="" /><span class="portfolio_zoom1"></span></a>
            </div>
          </li>
          <li class="item">
          	<div class="hover_img">
            	<a href="<%= image_url('placeholder/featured_works/1.jpg') %>" rel="prettyPhoto[portfolio1]"><img src="<%= image_url('placeholder/featured_works/1.jpg') %>" alt="" /><span class="portfolio_zoom1"></span></a>
            </div>
          </li>
          <li class="item">
          	<div class="hover_img">
            	<a href="<%= image_url('placeholder/featured_works/2.jpg') %>" rel="prettyPhoto[portfolio1]"><img src="<%= image_url('placeholder/featured_works/2.jpg') %>" alt="" /><span class="portfolio_zoom1"></span></a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!--//featured works-->

<!--Latest news-->
<div class="wrap block">
  <div class="container">
		<div class="row news_block">
			<div class="col-md-6">
    	  <h2 class="title">egestas sed convallis metus!</h2>
        <p>Vestibulum tincidunt ultricies aliquam. Donec porta mi nec tortor sagittis rhoncus. Nunc ante arcu, ornaresit gravida rutrum ut, facilisis et lacus. Aliquam mauris arcu, interdum eu fermentum tincidunt.</p>
        <ul class="the-icons grey">
        	<li><i class="glyphicon glyphicon-time"></i> Curabitur eu placerat massa.</li>
          <li><i class="glyphicon glyphicon-star"></i> Integer adipiscing velit nec purus facilisis ut pharetra!</li>
          <li><i class="glyphicon glyphicon-camera"></i> Nunc mollis, nisl vel tincidunt vestibulum, lacus libero mollis urna, eu dapibus lacus nisi et nulla.</li>
          <li><i class="glyphicon glyphicon-qrcode"></i> Curabitur veltpat magna. Pellentesque pellentesque dapibus dictum. </li>
          <li><i class="glyphicon glyphicon-user"></i> Nulla ut erat ut massa molestie commodo.</li>
        </ul>
        <p>Duis vel ligula et libero iaculis facilisis in vel justo. Duis lacinia orci ut tellus interdum dignissim. Fusce eugei scelerisque enim. Phasellus nec libero lectus. Quisque posuere mi non nibh facilisis semper. Donec lorem suscipit est sed mauris eleifend congue. Class taciti sociosqu litora torquent <a href="#" class="arrow_link">per conubia.</a></p>
      </div>
      <div class="col-md-6">
      	<h2 class="title">Latest news</h2>
        <ul id="newscarousel" class="owl-carousel owl-theme">
          <li class="item">
          	<div class="news_date">15 apr<span>2019</span></div>
            <div class="news_t"><a href="#">Sed massa dui, porta corper ac varius!</a></div>
            <div class="news">Posted by <a href="#">Anna Smith</a>  /  In <a href="#">City</a><br/>Tags: <a href="#">eget</a>, <a href="#">mauris</a></div>
            <div class="news_info">Tristique tincidunt cursus sed, ornare ncidunt eque a tristique. Phasellus porttitor mollis tortor etoq vestibulum. Quisque non lacus tortor, quis cumsan nibh. Lorem ipsum dolor sit amet, consectetur icing elit. Nullam pulvinarteses lorem sed dui euismod eget. <a href="#">Read more...</a></div>
            <div class="clear"></div>
          </li>
          <li class="item">
          	<div class="news_date">05 apr<span>2019</span></div>
            <div class="news_t"><a href="#">eget &amp; massa viviamu marius mas</a></div>
            <div class="news">Posted by <a href="#">Anna Smith</a>  /  In <a href="#">City</a><br/>Tags: <a href="#">eget</a>, <a href="#">mauris</a></div>
            <div class="news_info">Cursus sed, aliquet nec odio. Integer ornare tincidunt neque a tristique. Phasellus porttitor millis tortor etoq vestibulum. Quisque ont lacus toirtor uis accumsan nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ulvinarteses em sed. <a href="#">Read more...</a></div>
            <div class="clear"></div>
          </li>
          <li class="item">
          	<div class="news_date">15 apr<span>2019</span></div>
            <div class="news_t"><a href="#">Sed massa dui, porta corper ac varius!</a></div>
            <div class="news">Posted by <a href="#">Anna Smith</a>  /  In <a href="#">City</a><br/>Tags: <a href="#">eget</a>, <a href="#">mauris</a></div>
            <div class="news_info">Tristique tincidunt cursus sed, ornare ncidunt eque a tristique. Phasellus porttitor mollis tortor etoq vestibulum. Quisque non lacus tortor, quis cumsan nibh. Lorem ipsum dolor sit amet, consectetur icing elit. Nullam pulvinarteses lorem sed dui euismod eget. <a href="#">Read more...</a></div>
            <div class="clear"></div>
          </li>
          <li class="item">
          	<div class="news_date">05 apr<span>2019</span></div>
            <div class="news_t"><a href="#">eget &amp; massa viviamu marius mas</a></div>
            <div class="news">Posted by <a href="#">Anna Smith</a>  /  In <a href="#">City</a><br/>Tags: <a href="#">eget</a>, <a href="#">mauris</a></div>
            <div class="news_info">Cursus sed, aliquet nec odio. Integer ornare tincidunt neque a tristique. Phasellus porttitor millis tortor etoq vestibulum. Quisque ont lacus toirtor uis accumsan nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ulvinarteses em sed. <a href="#">Read more...</a></div>
            <div class="clear"></div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!--Latest news-->

<!--latest posts-->
<div class="wrap block carousel_block">
  <div class="container">
    <h2 class="upper">latest posts</h2>
    <div class="row">
      <div class="col-md-12">
        <ul id="carousel_post" class="owl-carousel owl-theme">
          <% # Load 6 most recent blog post #%>
          <li class="item">
          	<div>
            	<img src="<%= image_url('placeholder/home_blog/1.jpg') %>" alt="" />
            	<div class="title_t"><a href="#">ipsum dolor ac egestas mas</a></div>
              <div class="post_meta">
            		Posted by <a href="#">John Doe</a>  /  15 apr  / In <a href="#">Vacation</a>
              </div>
              Ut nisl turpis, tristique tincidunt cursus sed, aliquet nec odio. Integer ornare tincidunt neque a ristiquet phasellus mollis tortor. <a href="#" class="arrow_link">Read more...</a>
            </div>
          </li>
          <li class="item">
          	<div class="post_carousel">
            	<img src="<%= image_url('placeholder/home_blog/2.jpg') %>" alt="" />
            	<div class="title_t"><a href="#">vestibulum egestas tortor</a></div>
              <div class="post_meta">
            		Posted by <a href="#">John Doe</a>  /  15 apr  / In <a href="#">Vacation</a>
              </div>
              Ut nisl turpis, tristique tincidunt cursus sed, aliquet nec odio. Integer ornare tincidunt neque a ristiquet phasellus mollis tortor. <a href="#" class="arrow_link">Read more...</a>
            </div>
          </li>
          <li class="item">
            <div class="post_carousel">
            	<img src="<%= image_url('placeholder/home_blog/3.jpg') %>" alt="" />
            	<div class="title_t"><a href="#">Quisque sodales dolor</a></div>
              <div class="post_meta">
            		Posted by <a href="#">John Doe</a>  /  15 apr  / In <a href="#">Vacation</a>
              </div>
              Ut nisl turpis, tristique tincidunt cursus sed, aliquet nec odio. Integer ornare tincidunt neque a ristiquet phasellus mollis tortor. <a href="#" class="arrow_link">Read more...</a>
            </div>
          </li>
          <li class="item">
          	<div class="post_carousel">
            	<img src="<%= image_url('placeholder/home_blog/4.jpg') %>" alt="" />
            	<div class="title_t"><a href="#">ipsum dolor ac egestas mas</a></div>
              <div class="post_meta">
            		Posted by <a href="#">John Doe</a>  /  15 apr  / In <a href="#">Vacation</a>
              </div>
              Ut nisl turpis, tristique tincidunt cursus sed, aliquet nec odio. Integer ornare tincidunt neque a ristiquet phasellus mollis tortor. <a href="#" class="arrow_link">Read more...</a>
            </div>
          </li>
          <li class="item">
          	<div class="post_carousel">
            	<img src="<%= image_url('placeholder/home_blog/1.jpg') %>" alt="" />
            	<div class="title_t"><a href="#">Tristique cursus tincidunt</a></div>
              <div class="post_meta">
            		Posted by <a href="#">John Doe</a>  /  15 apr  / In <a href="#">Vacation</a>
              </div>
              Ut nisl turpis, tristique tincidunt cursus sed, aliquet nec odio. Integer ornare tincidunt neque a ristiquet phasellus mollis tortor. <a href="#" class="arrow_link">Read more...</a>
            </div>
          </li>
          <li class="item">
          	<div class="post_carousel">
            	<img src="<%= image_url('placeholder/home_blog/2.jpg') %>" alt="" />
            	<div class="title_t"><a href="#">ipsum dolor ac egestas mas</a></div>
              <div class="post_meta">
            		Posted by <a href="#">John Doe</a>  /  15 apr  / In <a href="#">Vacation</a>
              </div>
              Ut nisl turpis, tristique tincidunt cursus sed, aliquet nec odio. Integer ornare tincidunt neque a ristiquet phasellus mollis tortor. <a href="#" class="arrow_link">Read more...</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!--//latest posts-->

app/views/layouts/about.html.erb
<%= render 'layouts/shared/breadcrumb' %>
<div class="wrap">
  <div class="container">
    <section>
      <div class="row">
        <%= yield (:top) %>
      </div>
    </section>
    <section>
      <%= yield (:bottom) %>
    </section>
  </div>
</div>
<% parent_layout 'application' %>

app/views/layouts/application.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag params[:controller] %> 
<% end %>
<%= render partial: 'layouts/shared/header' %>

<!--page_container-->
<div class="page_container">
  <%= yield %>
</div>
<!--//page_container-->

<%= render partial: 'layouts/shared/footer' %>

<% content_for :javascript do %>
  <%= javascript_include_tag params[:controller] %>
<% end %>

<% parent_layout 'base' %>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= yield(:title) || ('site_name') | ('tag_line') %>
  </title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= yield(:head) %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="alert alert-info alert-dismissible"><%= flash.notice %></div>

  <%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield(:javascript) %>
</body>
</html>

app/views/layouts/shared/_breadcrumb.html.erb
<%# Render breadcrumb links based on location %>
<div class="breadcrumb">
  <div class="wrap">
  	<div class="container">
        <%= link_to 'Home', root_path %><span>/</span>About
    </div>
  </div>
</div>

app/views/layouts/shared/_footer.html.erb
<!--footer-->
<div id="footer">
  <div class="wrap">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <h2 class="title">Latest tweets</h2>
          <div class="tweet_block"></div>
        </div>
        <div class="col-md-3">
        	<h2 class="title">Get in touch!</h2>
          <form action="#" method="post">
          	<input class="form-control" type="text" name="name" id="name" value="Name" onFocus="if (this.value == 'Name') this.value = '';" onBlur="if (this.value == '') this.value = 'Name';" />
              <input class="form-control" type="text" name="email" id="email" value="Email" onFocus="if (this.value == 'Email') this.value = '';" onBlur="if (this.value == '') this.value = 'Email';" />
              <textarea name="message" id="message" class="form-control" onFocus="if (this.value == 'Message') this.value = '';" onBlur="if (this.value == '') this.value = 'Message';" >Message</textarea>
              <div class="clear"></div>
              <input type="reset" class="btn dark_btn" value="Clear form" />
              <input type="submit" class="btn send_btn" value="Send!" />
              <div class="clear"></div>
          </form>
        </div>
        <div class="col-md-3">
      	<h2 class="title">Testimonials</h2>
          <ul>
          	<li>
            	<span class="testimonials_arrow"></span>Orci nisi, luctus vitae imperdiet a, iquam vel urna. Pellentesque tincidunt laoreet est, in tristique sapien consequat a purus at ullamcorper pulvinar, massa libero magna.
            	<div class="clear"></div>
                <div class="author">Anna Smith, Company inc.</div>
            </li>
            <li>
            	<span class="testimonials_arrow"></span>Luctus vitae imperdiet a, iquamorci nisi lorem. Pellentesque tincidunt laoreet est, in tristique sapien consequat a purus at ullam pulvinar, massa libero consequat egestas mas.
            	<div class="clear"></div>
              <div class="author">John Doe, Company inc.</div>
            </li>
          </ul>
        </div>
        <div class="col-md-">
        	<h2 class="title">instagram photostream</h2>
            <div class="flickrs">
              <div class="FlickrImages">
                <ul></ul>
                <div class="clear"></div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>

  <div class="footer_bottom">
    <div class="wrap">
      <div class="container">
        <div class="row">
          <div class="col-md-5">
          	<div class="foot_logo"><%= link_to 'Home', root_path, class: 'foot_logo_link' %></div>
          	<div class="copyright">&copy; 2014 JUSS Media Professional Fashion Photography. All Rights Reserved.</div>
          </div>
          <div class="7">
            <div class="foot_right_block">
              <div class="fright">
                <form action="#" method="post">
                  <input class="inp_search" name="name" type="text" value="Search the Site" onfocus="if (this.value == 'Search the Site') this.value = '';" onblur="if (this.value == '') this.value = 'Search the Site';" />
                </form>
              </div>
              <div class="follow_us">
              	<ul>
                  <li><%= link_to "Facebook", 'http://fb.jussmedia.com', target: '_blank', class: 'facebook', rel: 'tooltip' %></li>
                  <li><%= link_to "Vimeo", 'http://vimeo.jussmedia.com', target: '_blank', class: 'vimeo', rel: 'tooltip' %></li>
                  <li><%= link_to "Tumblr", 'http://tumblr.jussmedia.com', target: '_blank', class: 'tumblr', rel: 'tooltip' %></li>
                  <li><%= link_to "Twitter", 'http://twitter.jussmedia.com', target: '_blank', class: 'twitter', rel: 'tooltip' %></li>
                  <li><%= link_to "Instagram", 'http://ig.jussmedia.com', target: '_blank', class: 'instagram', rel: 'tooltip' %></li>
                <ul>
              </div>
              <div class="clear"></div>

            	<div class="clear"></div>
            	<div class="foot_menu">
            		<ul>
                  <li class="current"><%= link_to 'Home', root_path %></li>
                  <li><%= link_to 'About', '#' %></li>
                  <li><%= link_to 'Portfolio', '#' %></li>
                  <li><%= link_to 'Blog', '#' %></li>
                  <li><%= link_to 'Contact', '#' %></li>
                </ul>
            	</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--//footer-->

app/views/layouts/shared/_header.html.erb
<div class="header">
  <div class="wrap">
  	<div class="navbar navbar_ clearfix">
    	<div class="container">
        <div class="row">
          <div class="col-md-4">
          	<div class="logo"><%= link_to image_tag('jussmedia-logo.png') %></div>
          </div>
          <div class="col-md-8">
          	<div class="follow_us">
              <ul>
                <li><%= link_to "Facebook", 'http://fb.jussmedia.com', target: '_blank', class: 'facebook' %></li>
                <li><%= link_to "Vimeo", 'http://vimeo.jussmedia.com', target: '_blank', class: 'vimeo' %></li>
                <li><%= link_to "Tumblr", 'http://tumblr.jussmedia.com', target: '_blank', class: 'tumblr' %></li>
                <li><%= link_to "Twitter", 'http://twitter.jussmedia.com', target: '_blank', class: 'twitter' %></li>
                <li><%= link_to "Instagram", 'http://ig.jussmedia.com', target: '_blank', class: 'instagram' %></li>
              </ul>
            </div>
            <div class="clear"></div>
            <nav id="main_menu">
              <div class="menu_wrap">
                <ul class="nav sf-menu">
                  <li class="current"><%= link_to 'Home', root_path %></li>
                  <li><%= link_to 'About', about_index_path %></li>
                  <li class="sub-menu"><a href="javascript:{}">Portfolio</a>
                    <ul>
                      <li><a href="#"><span>-</span>2 Columns</a></li>
                      <li><a href="#"><span>-</span>3 Columns</a></li>
                      <li><a href="#"><span>-</span>4 Columns</a></li>
                    </ul>
                  </li>
                  <li class="sub-menu"><%= link_to 'Blog', '#' %>
                   <ul>
                     <li><a href="#"><span>-</span>Blog with right sidebar</a></li>
                     <li><a href="#"><span>-</span>Blog post</a></li>
                   </ul>
                  </li>
                  <li>
                    <a href="#">Contact</a>
                  </li>
                </ul>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>